### ISSUE TITLE
Not able to find VAE implementation

### ISSUE THREAD

**Issue by Satishpas2** [Baileyswu/pytorch-hmm-vae#1]
Hi,
I searched in ur repo..but not ble to find out the VAE implementation with MFCC features.
It is only mentioned in .cgf file....but complete implementation is not there.
Could u plz provide the full implementation.
i will be obliged to u.
thanks in advance!

**Comment by Baileyswu** [comment]
As you can see in the file `cfg/TIMIT_baselines/TIMIT_MLP_mfcc_vae.cfg`, VAE is implemented as a combination of modulars [line 154](https://github.com/Baileyswu/pytorch-hmm-vae/blob/679c8202b1d19662e76497bbac865a703beacc84/cfg/TIMIT_baselines/TIMIT_MLP_mfcc_vae.cfg#L154)


line 156-163 is a VAE process.
